### ISSUE TITLE
并没有添加图片到序列

### ISSUE THREAD

**Issue by SettingDust** [feilongfl/muzei-pixivtop#4]
点击换源之后图片不会更换 Browse也是空的

**Comment by feilongfl** [comment]
![screenshot_20190207-061317_muzei](https://user-images.githubusercontent.com/10269596/52377373-a18c3d80-2a9f-11e9-94cf-a504a8151bb4.png)

emmm，无法复现啊，我试了三台手机和模拟器都挺正常的

**Comment by SettingDust** [comment]
Emmmm 我查看log貌似也没有什么报错出现？(可能方法错误)，甚至无请求。浏览器访问pixivic正常

![xx](https://i.imgur.com/LDEPQ45.jpg)
![””](https://i.imgur.com/PwiSXpP.jpg)

**Comment by feilongfl** [comment]
emmm 这就很有意思了,要不你点点那个右箭头试一试

[https://c-t.work/s/08e9f3c43ac444](https://c-t.work/s/08e9f3c43ac444)

**Comment by SettingDust** [comment]
@feilongfl 没有下一张图的操作键，点击快捷操作也无效，并无发包，我用另外一个直接走pixiv是正常的(就是要开着SSR)

**Comment by feilongfl** [comment]
😭你说下你手机的环境吧,网络电信/联通/移动,系统原生/华为/小米/其他?安卓版本?

**Comment by SettingDust** [comment]
@feilongfl 联通(pixivic正常)，oppo coloros5.2.1 Android 7.1.1。 我试试别人手机去……

**Comment by feilongfl** [comment]
额，oppo这个...没有 :sob: 人在老家，本人原生，爸爸小米，妈妈华为:joy:

**Comment by SettingDust** [comment]
忘了回复 Muzei 3.0.2 Nubia也失败了 网络更换过

**Comment by feilongfl** [comment]
@SettingDust 
:sob: nubia... 这个我也没有:cold_sweat: 

我这边muzei最新3.0.2手机play版，模拟器f-droid版（虽然这俩应该是一个）

**Comment by feilongfl** [comment]
我好像找到了这个问题的原因,请尝试访问https://pixivic.com/dailyRank

由于未知原因,接口返回空数组

request:
```
curl 'https://api.pixivic.com/d?page=0&date=2019-02-06' -H 'Pragma: no-cache' -H 'Origin: https://pixivic.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,zh-SG;q=0.8,zh-CN;q=0.7,zh;q=0.6,ja-JP;q=0.5,ja;q=0.4' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: https://pixivic.com/dailyRank' -H 'Connection: keep-alive' -H 'DNT: 1' --compressed
```

response
```
[]
```

**Comment by feilongfl** [comment]
请尝试下https://github.com/feilongfl/muzei-pixivtop/releases/tag/v0.0.3

**Comment by SettingDust** [comment]
那个页面确实为空，新的依旧无效

**Comment by feilongfl** [comment]
额,那看来并不是这个问题...

这个就比较复杂了...

![](https://user-images.githubusercontent.com/10269596/52515277-49e30300-2c54-11e9-8732-0285be7e187f.gif)

**Comment by SettingDust** [comment]
为什么返回是空的呢？ 网络请求有发出去，我手机抓包也失败XD

**Comment by SettingDust** [comment]
雾槽 成功了

**Comment by feilongfl** [comment]
![sticker](https://user-images.githubusercontent.com/10269596/52517553-e1a61880-2c77-11e9-8b70-a7b87e005064.jpg)
